const Products = [
    "Sacola",
    "Cachepot",
    "Saia",
    "Forminha luxo",
    "Forminha",
    "Vela X-Fire",
    "Bem",
    "Envelope para Convite",
    "Baleiro",
    "Cesta ",
    "Cesta ",
    "Canudo",
    "Gliter",
    "Inflador de bolas",
    "vela 0785",
    "vela 0784",
    "vela 0783",
    "vela 5466",
    "Petala",
    "Canudo metalizado",
    "etiquetas",
    "brinquedos",
    "Pulseira neon",
    "descartáveis",
    "Pulseira holografica",
    "placas divertidas",
    "adesivos",
    "faixa",
    "paineis",
    "fechamento de envelope",
    "lança confete"
];

export default Products;