export default [
    "coroa",
    "game",
    "laço",
    "estrela",
    "aranha",
    "homem verde",
    "coroa azul",
    "coroa rosa",
    "ratinho",
    "mulher poderosa",
    "mon bola",
    "mon laranja",
    "mon azul",
    "mon amarelo",
    "Festa junina",
    "tifani",
    "unicornio",
    "prata",
    "fazendinha",
    "vaquinha",
    "laço pink",
    "circo",
    "chuva",
    "melancia",
    "ouro"
];